export const CHAT_INITIALIZED = 'CHAT_INITIALIZED';

export const CHAT_SESSION_CONNECTED = 'CHAT_SESSION_CONNECTED';
export const CHAT_SESSION_DISCONNECTED = 'CHAT_SESSION_DISCONNECTED';
export const CHAT_SESSION_BROKEN = 'CHAT_SESSION_BROKEN';

export const REQUEST_MEMBER_MESSAGE_PUBLISH = 'REQUEST_MEMBER_MESSAGE_PUBLISH';
export const SUCCESS_MEMBER_MESSAGE_PUBLISH = 'SUCCESS_MEMBER_MESSAGE_PUBLISH';
export const FAILURE_MEMBER_MESSAGE_PUBISH = 'FAILURE_MEMBER_MESSAGE_PUBLISH';

export const REQUEST_TRANSCRIPT = 'REQUEST_TRANSCRIPT';
export const SUCCESS_TRANSCRIPT = 'SUCCESS_TRANSCRIPT';
export const FAILURE_TRANSCRIPT = 'FAILURE_TRANSCRIPT';

export const REQUEST_RETRY_SEND_MESSAGE = 'REQUEST_RETRY_SEND_MESSAGE';
export const REQUEST_SEND_MESSAGE = 'REQUEST_SEND_MESSAGE';
export const SUCCESS_SEND_MESSAGE= 'SUCCESS_SEND_MESSAGE';
export const FAILURE_SEND_MESSAGE = 'FAILURE_SEND_MESSAGE';

export const CLOSE_CHAT = 'CLOSE_CHAT'